# Generated by Django 4.2.7 on 2023-12-03 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendor_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_details', models.IntegerField(max_length=14)),
                ('address', models.CharField(max_length=150)),
                ('on_time_delivery_rate', models.FloatField(max_length=10)),
                ('quality_rating_avg', models.FloatField(max_length=10)),
                ('average_response_time', models.FloatField(max_length=10)),
                ('fulfillment_rate', models.FloatField(max_length=10)),
            ],
        ),
    ]
