# Generated by Django 4.2.7 on 2023-12-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_profile_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='contact_details',
            field=models.IntegerField(),
        ),
    ]
